### ISSUE TITLE
future of rust-zookeeper

### ISSUE THREAD

**Issue by softprops** [bonifaido/rust-zookeeper#1]
Is this project intended to be maintained in the future. rust stable is now about and it seems the source for this project has fell somewhat behind.

**Comment by bonifaido** [comment]
Hi,
yes I plan to maintain it, however I haven't had the chance to find a suitable replacement for the old Reader::read_be_XX methods, and of course lack of time, this project was developed in my free time. So any helps are welcome, for example, how to replace these low lever reading methods?

**Comment by softprops** [comment]
cool. If I can find the time myself, I'll try to help out and submit a pull. Nice work on this btw

**Comment by bonifaido** [comment]
I think this might be a solution for our problems, I will take a look at it:
https://github.com/andydude/rust-endian/

**Comment by bonifaido** [comment]
Made the build green again with 98db2dc, so it compile against rust nightly currently, I wanted stay on stable, it was easier to migrate to the nightly and most probably those features will arrive in 1.1.

**Comment by bonifaido** [comment]
Released 0.1.0 which runs smoothly now with latest nightly.
If you need compatibility with another release channel please drop an issue again.

**Comment by softprops** [comment]
Thanks for the quick turn around!

**Comment by bonifaido** [comment]
You're welcome, and thanks for reminding me that this was broken.
