### ISSUE TITLE
Validate that serialization is fully correct

### ISSUE THREAD

**Issue by rgs1** [bonifaido/rust-zookeeper#12]
While playing with the library while writing https://github.com/rgs1/zk-shell-rs, all seems to work. Though when trying to capture packets via zk-dump (https://github.com/twitter/zktraffic), I don't see anything (see https://github.com/twitter/zktraffic/issues/56).

I'll keep digging to make sure that rust-zookeeper is generating correct jute serialized packets (though, given that the server does see my commands, it seems to be right - but there might be some bugs).

**Comment by bonifaido** [comment]
I have installed zk-dump on OS X (I haven't used it before), and tried to capture some packages like this:
```zkServer start```
```sudo zk-dump --iface=lo0```
```zkCli ...generate some traffic```
But I haven't seen anything captured, what am I doing wrong?

**Comment by rgs1** [comment]
Weird. This is in Linux:

Via zk-shell:

```
$ zk-shell 0 
Welcome to zk-shell (1.0.08)
(CONNECTING) /> 
(CONNECTED) /> get /
(CONNECTED) /> 
```

And the dump:

```
$ sudo zk-dump --iface lo --include-pings
13:29:54:686692 ConnectRequest(ver=0, zxid=0, timeout=10000, session=0x0, readonly=False, client=127.0.0.1:39152)
————►13:29:54:689953 ConnectReply(ver=0, timeout=10000, session=0x14edb8176ec0001, readonly=False, server=127.0.0.1:2181)
13:29:56:032068 ExistsRequest(xid=1, path=/, watch=False, size=14, client=127.0.0.1:39152)
————►13:29:56:039765 ExistsReply(xid=1, zxid=25, error=0, server=127.0.0.1:2181)
13:29:56:040394 GetDataRequest(xid=2, path=/, watch=False, size=14, client=127.0.0.1:39152)
————►13:29:56:043961 GetDataReply(xid=2, zxid=25, error=0, server=127.0.0.1:2181)
13:29:59:241200 PingRequest(client=127.0.0.1:39152)
————►13:29:59:244187 PingReply(xid=-2, zxid=25, error=0, server=127.0.0.1:2181)
```

Maybe @Yasumoto knows if it's broken in OS X.

**Comment by rgs1** [comment]
Oh, I think it's because there are multiple write() calls, which ends up putting the data in multiple IP packets (zk-dump assumes things are packed, as is the case for the Java/C/Python implementations):

https://github.com/bonifaido/rust-zookeeper/blob/master/src/proto.rs#L60

It would be nice to do one write() call on the socket (or use some abstraction on top that buffers and then flushes all at once), both for performance and to behave like other implementations.

**Comment by rgs1** [comment]
I guess the easiest way would be to write_to() the Vec<u8> a dummy i32 (i.e.: 0), and then set the len after serializing everything else.

**Comment by bonifaido** [comment]
I think this should solve the issue, however I wasn't able to test it because zk-dump doesn't really work on my machine. :(

**Comment by rgs1** [comment]
That fixed the problem, I can now see traffic from zk-shell-rs using rust-zookeeper:

```
$ sudo zk-dump --iface=lo  --include-pings
09:30:16:526105 ConnectRequest(ver=0, zxid=0, timeout=5000, session=0x0, readonly=False, client=127.0.0.1:34406)
————►09:30:16:532630 ConnectReply(ver=0, timeout=5000, session=0x14ec33c0aa0002a, readonly=False, server=127.0.0.1:2181)
09:30:19:866042 PingRequest(client=127.0.0.1:34406)
————►09:30:19:868137 PingReply(xid=-2, zxid=106, error=0, server=127.0.0.1:2181)
09:30:22:211409 GetDataRequest(xid=1, path=/foo, watch=False, size=17, client=127.0.0.1:34406)
————►09:30:22:213673 FailedGetDataReply(xid=1, zxid=106, error=-101, server=127.0.0.1:2181)
09:30:23:199073 PingRequest(client=127.0.0.1:34406)
————►09:30:23:201197 PingReply(xid=-2, zxid=106, error=0, server=127.0.0.1:2181)
09:30:23:989621 GetDataRequest(xid=2, path=/bar, watch=False, size=17, client=127.0.0.1:34406)
————►09:30:23:989862 GetDataReply(xid=2, zxid=106, error=0, server=127.0.0.1:2181)
09:30:26:532051 PingRequest(client=127.0.0.1:34406)
————►09:30:26:534137 PingReply(xid=-2, zxid=106, error=0, server=127.0.0.1:2181)
09:30:29:865042 PingRequest(client=127.0.0.1:34406)
————►09:30:29:865199 PingReply(xid=-2, zxid=107, error=0, server=127.0.0.1:2181)
09:30:33:198045 PingRequest(client=127.0.0.1:34406)
————►09:30:33:200072 PingReply(xid=-2, zxid=107, error=0, server=127.0.0.1:2181)
09:30:36:531049 PingRequest(client=127.0.0.1:34406)
————►09:30:36:533080 PingReply(xid=-2, zxid=107, error=0, server=127.0.0.1:2181)
09:30:36:798880 SetDataRequest(xid=4, path=/bar, watch=False, size=28, client=127.0.0.1:34406)
————►09:30:36:801333 SetDataReply(xid=4, zxid=108, error=0, server=127.0.0.1:2181)
```

My only comment about the fix would be that, it makes an extra copy of the ```Vec<u8>``` so it might not be super performant under heavy load (i.e.: imagine a lot of big writes, i.e.: bigger > 512Kb). 

But we can fix that later on. Not sure about what's up with zk-dump in OS X, I suspect you might be missing a dependency. 

Thanks for the fix!

**Comment by bonifaido** [comment]
Made it more performant, yeah I didn't like the idea of copying it again.
