### ISSUE TITLE
Any plans on command-line utility

### ISSUE THREAD

**Issue by tailhook** [bonifaido/rust-zookeeper#25]
Hi,

I need some command-line utility to run simple zookeeper queries. I think this library is a good base for it.  

The reason I don't want to use default zookeeper cli and zk-shell because they depend on java and python respectively. In rust we can make a static (or almost static) binary to run commands.

So do you want me to make a PR with some small command-line client or do you think it's better to keep it as a separate project?

**Comment by rgs1** [comment]
I started this:

https://github.com/rgs1/zk-shell-rs

But it's nowhere near what the Python version offers:

https://github.com/rgs1/zk_shell

The basics work though, and it shouldn't be that hard to port the missing features.

**Comment by tailhook** [comment]
Good. It's probably good idea to contribute to zk-shell-rs.

**Comment by bonifaido** [comment]
Hi, yeah I think it's better to have it as a separate project.
