### ISSUE TITLE
Infinite Loop 

### ISSUE THREAD

**Issue by f3r10** [bonifaido/rust-zookeeper#26]
Hello!!
When zookeeper is running the lib working good but when zookeeper is not running the lib response with a infinite loop: "ERROR:zookeeper::io: Failed to write socket: Error { repr: Os { code: 57, message: "Socket is not connected" } }"
There any way to control and finish when  this error occurs?

Thanks in advance!!

**Comment by csaltos** [comment]
👍

**Comment by bonifaido** [comment]
ZooKeeper clients tend to try reconnecting to the server for a certain amount of time, so they don't finish right after the connection loss (at least session timeout long they try).
This is not implemented in the lib right now, but pull requests are welcome! :)
I would start here (see TODO): https://github.com/bonifaido/rust-zookeeper/blob/master/src/io.rs#L235

**Comment by bonifaido** [comment]
I have created a fix, please check it out in the new version (2.0.1), it is still not perfect but much better than previously. You can use the `ZooKeeper::add_listener()` to listen to `Closed` events.
