### ISSUE TITLE
Create statics for predefined Acls and Ids

### ISSUE THREAD

**Issue by bonifaido** [bonifaido/rust-zookeeper#3]
Try experimenting with lazy_static! because these are complex structures.

**Comment by rgs1** [comment]
Thanks for writing this library! I've started creating a shell on top of it (similar to https://github.com/rgs1/zk-shell):

https://github.com/rgs1/zk-shell-rs

Hopefully I'll have some feedback/pull-requests shortly ;-)

**Comment by bonifaido** [comment]
Thank you, I wil check it out! :)
Does this mean you would like to see these predefined statics implemented?

**Comment by rgs1** [comment]
That would definitely help!

**Comment by rgs1** [comment]
Would it be hard to make ACL implement Clone? Right now, I have to create a new vec![Acl{}] every time I call create:

https://github.com/rgs1/zk-shell-rs/blob/master/src/shell.rs#L156

**Comment by bonifaido** [comment]
I just pushed predefined Acls and the deriving of the Clone trait in f6985fa (just messed up the issue reference in the commit).
Please review if it fits your needs and common use case.
Ultimately I think I should have designed the API to be pass by reference instead of pass by value for all non-primitive parameters, what do you think?

**Comment by rgs1** [comment]
Thanks! Passing by reference makes sense to me. I guess it depends on how the async API is going to look. Have you thought about that? Maybe returning a future?

**Comment by bonifaido** [comment]
Yes, but not deeply, I like the idea of Futures, but my only issue is they are deprecated: https://doc.rust-lang.org/nightly/std/sync/struct.Future.html
Are there any replacements already?

**Comment by bonifaido** [comment]
Anyhow, if you are happy with the constants (I am), I would like to close this one and take the discussion about the async workflow into #5

**Comment by rgs1** [comment]
Yup - lets do that. Thanks!
