### ISSUE TITLE
ZkError does not implement std::error::Error

### ISSUE THREAD

**Issue by drusellers** [bonifaido/rust-zookeeper#30]
Is this by design or something that you would take a pull request for?

**Comment by bonifaido** [comment]
Absolutely by mistake!

**Comment by drusellers** [comment]
Ok! I'll submit a PR this weekend! Heck yeah. 






On Sat, Nov 12, 2016 at 12:30 PM -0600, "Nándor István Krácser" <notifications@github.com> wrote:










Absolutely by mistake!
