### ISSUE TITLE
Subscription is hidden

### ISSUE THREAD

**Issue by UnlawfulMonad** [bonifaido/rust-zookeeper#34]
The `Zookeeper` struct leaks information in the form of `Subscription`. Since the module `Subscription` is in is not public the docs don't show anything except for an opaque struct (that can't be imported or stored anywhere). I'd be happy to submit a PR fixing this.

Would exposing it in the crate root (`pub use listeners::Subscription` in lib.rs) or should `listeners` be made public and the rest of the things in there use a `pub(crate)` modifier to hide them from the outside world?

**Comment by bonifaido** [comment]
Hi, good catch! I think `pub export listeners::Subscription` would be a nice solution. Looking forward for the PR.
