### ISSUE TITLE
Incorrect maintenance of zxid

### ISSUE THREAD

**Issue by jonhoo** [bonifaido/rust-zookeeper#50]
The code currently blindly adopts the `zxid` of each new received header:

https://github.com/bonifaido/rust-zookeeper/blob/a43f686a27a91461a374f0d65c732930dfb36084/src/io.rs#L176

However, as I recently [discovered while implementing `tokio-zookeeper`](https://youtu.be/0-Fsu-aM0_A?t=20542), watch events actually yield a `zxid` response of `-1`! This means that, if you were to crash right after handling a watch event, and then reconnect, you would reconnect with `zxid = -1`, which is not the right value.

It think the code needs to be changed so that it instead adopts the `zxid` only if the response is *not* a watcher event.

**Comment by tgockel** [comment]
Good find. The Java client check for >0 in [`ClientCnxn`](https://github.com/apache/zookeeper/blob/master/src/java/main/org/apache/zookeeper/ClientCnxn.java#L904) and the C client checks for > 0 [in the IO processing call](https://github.com/apache/zookeeper/blob/master/src/c/src/zookeeper.c#L2899). Seems like the right thing to do here.

**Comment by bonifaido** [comment]
I absolutely agree, this one was missed out!

**Comment by bonifaido** [comment]
Fixed already by @tgockel .
