### ISSUE TITLE
Publish new release of zookeeper_derive

### ISSUE THREAD

**Issue by jonhoo** [bonifaido/rust-zookeeper#52]
Following #49, I think you may also need to cut a new release of `zookeeper_derive`. The version argument included in `/Cargo.toml` seems to cause cargo to use `zookeeper_derive` from crates.io rather than the one included with zookeeper, which uses the old syn and quote dependencies.

**Comment by bonifaido** [comment]
Just fixed in https://github.com/bonifaido/rust-zookeeper/commit/79fd17db13059c0cf5d031dedccabd8a122eab67.
